#!/usr/bin/env bash

# Provision zsh + oh-my-zsh + plugins for the guest `admin` user.
# Relies on helpers sourced by scripts/tart/provision-dev-vm.sh:
#   - retry_command
#   - remo_tart_worktree_env_exports

readonly REMO_TART_SHELL_OMZ_INSTALL_URL="https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
readonly REMO_TART_SHELL_ZSH_PATH="/bin/zsh"
readonly REMO_TART_SHELL_GUEST_USER="${REMO_TART_GUEST_USERNAME:-admin}"

readonly REMO_TART_SHELL_ZSHRC_TEMPLATE='export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="clean"
plugins=(
  git macos rust node npm xcode gh
  zsh-autosuggestions zsh-syntax-highlighting zsh-completions
)
source "$ZSH/oh-my-zsh.sh"

[[ -f "$HOME/.remo-worktree-env.sh" ]] && source "$HOME/.remo-worktree-env.sh"
'

_shell_ensure_login_shell() {
    local current
    current="$(dscl . -read "/Users/${REMO_TART_SHELL_GUEST_USER}" UserShell 2>/dev/null | awk '{print $2}')"
    if [[ "${current}" == "${REMO_TART_SHELL_ZSH_PATH}" ]]; then
        return 0
    fi
    retry_command \
        "set zsh as login shell for ${REMO_TART_SHELL_GUEST_USER}" \
        sudo dscl . -create "/Users/${REMO_TART_SHELL_GUEST_USER}" UserShell "${REMO_TART_SHELL_ZSH_PATH}"
}

_shell_ensure_oh_my_zsh() {
    if [[ -d "${HOME}/.oh-my-zsh" ]]; then
        return 0
    fi
    retry_command \
        "install oh-my-zsh" \
        /bin/sh -c "sh -c \"\$(curl -fsSL ${REMO_TART_SHELL_OMZ_INSTALL_URL})\" \"\" --unattended --keep-zshrc"
}

_shell_ensure_plugin() {
    local name repo dest
    name="$1"
    repo="$2"
    dest="${HOME}/.oh-my-zsh/custom/plugins/${name}"
    if [[ -d "${dest}" ]]; then
        return 0
    fi
    retry_command \
        "clone ${name} plugin" \
        git clone --depth 1 "${repo}" "${dest}"
}

_shell_ensure_plugins() {
    _shell_ensure_plugin "zsh-autosuggestions" \
        "https://github.com/zsh-users/zsh-autosuggestions.git"
    _shell_ensure_plugin "zsh-syntax-highlighting" \
        "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    _shell_ensure_plugin "zsh-completions" \
        "https://github.com/zsh-users/zsh-completions.git"
}

_shell_render_zshrc() {
    local zshrc current_hash target_hash backup
    zshrc="${HOME}/.zshrc"
    target_hash="$(printf '%s' "${REMO_TART_SHELL_ZSHRC_TEMPLATE}" | shasum -a 256 | awk '{print $1}')"

    if [[ -f "${zshrc}" ]]; then
        current_hash="$(shasum -a 256 "${zshrc}" | awk '{print $1}')"
        if [[ "${current_hash}" == "${target_hash}" ]]; then
            return 0
        fi
        backup="${zshrc}.remo-backup.$(date +%Y%m%dT%H%M%S)"
        mv "${zshrc}" "${backup}"
    fi

    printf '%s' "${REMO_TART_SHELL_ZSHRC_TEMPLATE}" > "${zshrc}"
}

_shell_write_worktree_env() {
    local worktree_root env_file
    worktree_root="$1"
    env_file="${HOME}/.remo-worktree-env.sh"

    {
        printf '# Generated by .tart/packs/shell.sh — do not edit by hand.\n'
        remo_tart_worktree_env_exports "${worktree_root}"
        printf 'export PATH="$HOME/.cargo/bin:$PATH"\n'
    } > "${env_file}"
}

tart_pack_shell_ensure() {
    local worktree_root
    worktree_root="$1"

    _shell_ensure_login_shell
    _shell_ensure_oh_my_zsh
    _shell_ensure_plugins
    _shell_render_zshrc
    _shell_write_worktree_env "${worktree_root}"
}

tart_pack_shell_verify_toolchain() {
    zsh --version
    dscl . -read "/Users/${REMO_TART_SHELL_GUEST_USER}" UserShell
    ls "${HOME}/.oh-my-zsh/custom/plugins"
}
